function Regressor = trainForcingModel(vrTrain,vrVal,method,opt)

arguments
    vrTrain (:,:)
    vrVal (:,:)
    method {mustBeMember(method,["RandomForestRegressor","RegressionTree",...
        "RegressionTreeOptim","MultilayerPerceptron","LSTM"])} = "RandomForestRegressor"
    opt.MaxNumSplits (1,1) {mustBePositive} = 20;
    opt.TreeSize (1,1) {mustBePositive} = 20;
end

switch method
    case "RandomForestRegressor"

        Regressor = TreeBagger( ...
            opt.TreeSize, ...
            vrTrain{1},vrTrain{2}, ...
            'Method','regression');

    case "RegressionTree"
        
        tree = templateTree('MaxNumSplits',opt.MaxNumSplits);

        Regressor = fitrensemble( ...
            vrTrain{1},vrTrain{2}, ...
            'Learners',tree, ...
            'NumLearningCycles',20);

    case "RegressionTreeOptim"

        tree = templateTree( ...
            'MaxNumSplits',opt.MaxNumSplits,...
            'Reproducible',true);

        Regressor = fitrensemble(vrTrain{1},vrTrain{2}, ...
            'OptimizeHyperparameters','auto', ...
            'Learners',tree, ...
            'HyperparameterOptimizationOptions', ...
            struct('AcquisitionFunctionName','expected-improvement-plus'));

    case "MultilayerPerceptron"
        
        inputSize = size(vrTrain{1},2);

        layers = [
            sequenceInputLayer(inputSize,'Normalization','zscore')
            fullyConnectedLayer(20)
            reluLayer
            fullyConnectedLayer(1)
            regressionLayer
            ];

        options = trainingOptions('adam', ...
            'Plots','none', ...
            'Verbose',true, ...
            'OutputNetwork','best-validation-loss', ...
            'Shuffle','every-epoch', ...
            'MaxEpochs',200, ...
            'InitialLearnRate',1e-2, ...
            'LearnRateDropFactor',1, ...
            'LearnRateSchedule','piecewise', ...
            'GradientThreshold',1, ...
            'ValidationData',{vrVal{1}',vrVal{2}'}, ...
            'ValidationFrequency',1e2 ...
            );

        [Regressor,info] = trainNetwork(vrTrain{1}',vrTrain{2}',layers,options);

    case "LSTM"

        inputSize = size(vrTrain{1},2);

        layers = [
            sequenceInputLayer(inputSize,'Normalization','zscore')
            lstmLayer(10,'BiasInitializer','narrow-normal')
            fullyConnectedLayer(1)
            regressionLayer
            ];

        options = trainingOptions('adam', ...
            'Plots','none', ...
            'Verbose',true, ...
            'OutputNetwork','best-validation-loss', ...
            'Shuffle','every-epoch', ...
            'MaxEpochs',100, ...
            'InitialLearnRate',1e-2, ...
            'LearnRateDropFactor',1, ...
            'LearnRateSchedule','piecewise', ...
            'GradientThreshold',1, ...
            'ValidationData',{vrVal{1}',vrVal{2}'}, ...
            'ValidationFrequency',1e2 ...
            );

        [Regressor,info] = trainNetwork(vrTrain{1}',vrTrain{2}',layers,options);
end

% switch method
%     case "MultilayerPerceptron"
%         disp("Validation RMSE: "+info.FinalValidationRMSE)
%     otherwise
%         disp("Resubstitution Loss: "+resubLoss(Regressor))
% end

end